export const PERMISSIONS = [
  "dashboard:view",
  "products:view",
  "products:manage",
  "products:import",
  "categories:view",
  "categories:manage",
  "orders:view",
  "orders:update",
  "users:about:view",
  "users:about:manage",
  "users:ledger:view",
  "users:ledger:manage",
  "users:branches:view",
  "users:branches:manage",
  "users:permissions:view",
  "users:permissions:manage",
  "users:view",
  "users:manage",
  "wallet:topups:view",
  "wallet:topups:create",
  "wallet:manage",
  "announcements:view",
  "announcements:manage",
  "coupons:view",
  "coupons:manage",
  "settings:view",
  "settings:manage",
  "branches:view",
  "branches:manage",
  "audit:view",
  "uploads:auth",
] as const;

export type Permission = (typeof PERMISSIONS)[number];
